const ARGS = {
  varchar1: "VARCHAR(1)",
  varchar5: "VARCHAR(5)",
  varchar20: "VARCHAR(20)",
  varchar50: "VARCHAR(50)",
  varchar100: "VARCHAR(100)",
  varchar200: "VARCHAR(200)",
  varchar500: "VARCHAR(500)",
  notNull: "NOT NULL",
  serial: "SERIAL",
  primaryKey: "PRIMARY KEY",
  smallInt: "SMALLINT",
  int: "INT",
  bool: "BOOLEAN",
  bigInt: "BIGINT",
  unique: "UNIQUE",
  foreignKey: "FOREIGN KEY",
  date: "DATE",
  time: "TIME",
  numeric73: "NUMERIC(7, 3)",
  numeric83: "NUMERIC(8, 3)",
  numeric: "NUMERIC",
  array: "ARRAY",
  text: "TEXT",
  uuid: "UUID",
  uuid4: "DEFAULT uuid_generate_v4 ()",
  uuid1: "DEFAULT uuid_generate_v1 ()",

  cascade: "CASCADE",
  foreignKeyArray: "FOREIGN KEY[]",
  bigIntArray: `BIGINT[]`,
  textArray: `TEXT[]`,
  smallIntArray: `SMALLINT[]`,
  numericArray: `NUMERIC[]`,
  intArray: `INT[]`,
  jsonb: "JSONB"
};

export default ARGS;
